name: "Test Cron Job"

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  Jar-Build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Java version
        run: java -version

      - name: Set JAVA_HOME
        run: |
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          echo "JAVA_HOME is set to $JAVA_HOME"

      - name: Print current directory
        run: pwd

      - name: List files
        run: ls -al

      - name: Jar Build
        run: |
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          cd caseservice
          chmod 755 gradlew
          ./gradlew clean build -x test
