name: SQL Server Connection Test

on:
  push:
    branches:
      - test-windows-server

jobs:
  test-sql-connection:
    runs-on: zilverton-private-x64-windows

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORDSQL: ${{ secrets.PASSWORDSQL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # ✅ This clones your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ODBC Driver and pyodbc
        run: |
          choco install -y microsoft-odbc-driver-18-for-sql-server
          pip install pyodbc

      - name: List ODBC Drivers (for verification)
        run: |
          python -c "import pyodbc; print('Available ODBC Drivers:', pyodbc.drivers())"

      - name: Run SQL Server Connection Test
        run: |
          python test_sql_connection.py
