name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      TF_VAR_namespace:
        description: 'Subscription type for deployment'
        required: true
        default: 'nonprod'
        type: choice
        options:
          - nonprod
          - stage
          - prod

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Dynamic Values Based on Environment
      run: |
        echo "Setting environment-specific values..."
        echo "RESOURCE_ENV=${{ github.event.inputs.TF_VAR_namespace }}" >> $GITHUB_ENV

    - name: Set Azure Account Subscription
      run: |
        echo "Setting subscription for $RESOURCE_ENV"
        if [ "$RESOURCE_ENV" == "prod" ]; then
          az account set --subscription "PROD_SUBSCRIPTION_ID"
        elif [ "$RESOURCE_ENV" == "nonprod" ]; then
          az account set --subscription "NONPROD_SUBSCRIPTION_ID"
        elif [ "$RESOURCE_ENV" == "stage" ]; then
          az account set --subscription "STAGE_SUBSCRIPTION_ID"
        else
          echo "Invalid environment selected!"
          exit 1
        fi

    - name: Check if Resource Group Exists
      id: check_rg
      run: |
        echo "Checking if Resource Group exists for $RESOURCE_ENV..."
        az group exists --name crs-${RESOURCE_ENV}-tfstate-rg

    - name: Check Storage Account Availability
      id: check_storage
      run: |
        echo "Checking storage account availability for $RESOURCE_ENV..."
        az storage account check-name --name crs${RESOURCE_ENV}prodstorageacct
        az storage container exists --account-name crs${RESOURCE_ENV}prodstorageacct --name crs-${RESOURCE_ENV}-tfstate-container
