
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: "Select Environment"
        required: true
        default: "pflqa00"
        type: choice
        options:
          - pflqa00
          - pflqa12
          - pflqa22
          - pflqa36
          - pflqa42

jobs:
  deploy:
    runs-on: test
    steps:
      - name: Set Environment Variables
        run: |
          if [[ "${{ github.event.inputs.Environment }}" == "pflqa36" ]]; then
            echo "ADMIN_USR=pfmgr4" >> $GITHUB_ENV
            echo "PATH_ENV=pflqa36/" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.Environment }}" == "pflqa42" ]]; then
            echo "ADMIN_USR=pfmgr4" >> $GITHUB_ENV
            echo "PATH_ENV=pflqa42/" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.Environment }}" == "pflqa00" ]]; then
            echo "ADMIN_USR=pfmgr" >> $GITHUB_ENV
            echo "PATH_ENV=pflqa00/" >> $GITHUB_ENV
          else
            echo "Invalid environment choice: ${{ github.event.inputs.Environment }}"
            exit 1
          fi

      - name: Print Selected Variables
        run: |
          echo "Selected Admin User: $ADMIN_USR"
          echo "Selected Path: $PATH_ENV"
