name: Test SQL Server Network Connectivity

on: workflow_dispatch

jobs:
  network-test:
    runs-on: windows-latest

    steps:
      - name: Ping SQL Server
        shell: powershell
        run: |
          $server = "HSTNCMSRDIDEV01.healthspring.inside"
          Write-Host "Pinging $server..."
          if (Test-Connection -ComputerName $server -Count 2 -Quiet) {
            Write-Host "✅ Ping successful"
          } else {
            Write-Host "❌ Ping failed"
            exit 1
          }

      - name: Test Port 1433 (SQL Server)
        shell: powershell
        run: |
          $server = "HSTNCMSRDIDEV01.healthspring.inside"
          $port = 1433
          Write-Host "Testing port $port on $server..."
          $tcpTest = Test-NetConnection -ComputerName $server -Port $port
          if ($tcpTest.TcpTestSucceeded) {
            Write-Host "✅ Port $port is open"
          } else {
            Write-Host "❌ Port $port is closed or unreachable"
            exit 1
          }
