name: "Jar Build"

on:
  workflow_dispatch:

jobs:
  Jar-Build:
    runs-on: dev004-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java version
        run: |
          java -version
          javac -version

      - name: Print current directory
        run: pwd

      - name: List files
        run: ls -al

      - name: Jar Build
        env:
          JAVA_HOME: /home/bambscm1/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
          GRADLE_OPTS: "-Dorg.gradle.java.home=/home/bambscm1/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.14-7/x64"
        run: |
          export JAVA_HOME=${JAVA_HOME}
          export PATH="${JAVA_HOME}/bin:$PATH"
          echo "JAVA_HOME is set to $JAVA_HOME"

          cd caseservice
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon --stacktrace \
            -Dorg.gradle.jvmargs="--add-opens jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED"
          cd ..

          cd ddrgenerator
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon --stacktrace \
            -Dorg.gradle.jvmargs="--add-opens jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED"
