name: SQL Server Connection Test

on:
  push:
    branches:
      - test-windows-server

jobs:
  test-sql-connection:
    runs-on: zilverton-private-x64-windows

    env:
      SQL_SERVER: HSTNCMSRDIDEV01.healthspring.inside
      SQL_USERNAME: ${{ secrets.USERNAME }}
      SQL_PASSWORD: ${{ secrets.PASSWORDSQL }}

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install ODBC Driver and pyodbc
      run: |
        choco install -y microsoft-odbc-driver-18-for-sql-server
        pip install pyodbc

    - name: List ODBC Drivers (for verification)
      run: |
        import pyodbc
        print("Available ODBC Drivers:", pyodbc.drivers())
      shell: python

    - name: Run SQL Server Connection Test
      run: |
        import pyodbc
        conn_str = (
          "DRIVER={ODBC Driver 18 for SQL Server};"
          "SERVER=${{ env.SQL_SERVER }};"
          "DATABASE=master;"
          "UID=${{ env.SQL_USERNAME }};"
          "PWD=${{ env.SQL_PASSWORD }};"
          "TrustServerCertificate=yes;"
          "Trusted_Connection=no;"
        )
        try:
          conn = pyodbc.connect(conn_str, timeout=5)
          cursor = conn.cursor()
          cursor.execute("SELECT @@VERSION")
          row = cursor.fetchone()
          print("✅ Connected to SQL Server:")
          print(row[0])
          conn.close()
        except Exception as e:
          print("❌ Connection failed:", e)
          exit(1)
      shell: python
