name: Restart PAT Services

on:
  workflow_dispatch:

jobs:
  restart-pat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envName: [pfnz, pfid, pfth, pfph, pfsg, pfhk, pfau, pfbp, omau, pfgb, pffi, pfpt, pfes, pfra, pffr, pfde, pfch, pfit, omca, pfca, pfco, pfpr, pfcl, pfbr, pfmx, pfxu, pfus]
    if: ${{ github.event.inputs[matrix.envName] == 'true' }}
    steps:
      - name: Map admin user and environment info
        id: map
        run: |
          declare -A ADMINS=(
            [pfnz]=pfnzsup3 [pfid]=pfidsup3 [omca]=omcasup3 [pfhk]=pfhksup3 [pffi]=pffisup3 [pfco]=pfcosup3 [pfpr]=pfprsup3 [pfcl]=pfclsup3
            [pfbr]=pfbrsup3 [pfca]=pfcasup3 [pfph]=pfphsup3 [pfth]=pfthsup3 [pfsg]=pfsgsup3 [pfmx]=pfmxsup3 [pfxu]=pfxusup3 [pfus]=pfussup3
            [pfra]=pfrasup3 [pfgb]=pfgbsup3 [pfau]=pfausup3 [pfpt]=pfptsup3 [pfes]=pfessup3 [pffr]=pffrsup3 [pfde]=pfdesup3 [pfch]=pfchsup3
            [pfit]=pfitsup3 [pfbp]=pfbpsup3 [omau]=omausup3
          )
          declare -A SERVERS=(
            [pfnz]=daylnxcpsp023 [pfid]=daylnxcpsp023 [omca]=daylnxcpsp014 [pfhk]=daylnxcpsp023 [pffi]=daylnxcpsp022 [pfco]=daylnxcpsp014
            [pfpr]=daylnxcpsp014 [pfcl]=daylnxcpsp014 [pfbr]=daylnxcpsp014 [pfca]=daylnxcpsp014 [pfph]=daylnxcpsp023 [pfth]=daylnxcpsp023
            [pfsg]=daylnxcpsp023 [pfmx]=daylnxcpsp014 [pfxu]=daylnxcpsp014 [pfus]=daylnxcpsp014 [pfra]=daylnxcpsp022 [pfgb]=daylnxcpsp022
            [pfau]=daylnxcpsp023 [pfpt]=daylnxcpsp022 [pfes]=daylnxcpsp022 [pffr]=daylnxcpsp022 [pfde]=daylnxcpsp022 [pfch]=daylnxcpsp022
            [pfit]=daylnxcpsp022 [pfbp]=daylnxcpsp023 [omau]=daylnxcpsp023
          )
          declare -A PORTS=(
            [pfnz]=8152 [pfid]=8159 [omca]=8151 [pfhk]=8163 [pffi]=8154 [pfco]=8155 [pfpr]=8156 [pfcl]=8157
            [pfbr]=8158 [pfca]=8150 [pfph]=8160 [pfth]=8161 [pfsg]=8162 [pfmx]=8164 [pfxu]=8165 [pfus]=8166
            [pfra]=8167 [pfgb]=8153 [pfau]=8174 [pfpt]=8168 [pfes]=8169 [pffr]=8170 [pfde]=8171 [pfch]=8172
            [pfit]=8173 [pfbp]=8175 [omau]=8176
          )
          echo "adminuser=${ADMINS[${{ matrix.envName }}]}" >> $GITHUB_ENV
          echo "server=${SERVERS[${{ matrix.envName }}]}" >> $GITHUB_ENV
          echo "server_port=${PORTS[${{ matrix.envName }}]}" >> $GITHUB_ENV

      - name: Kill and restart PAT service
        run: |
          ssh -o StrictHostKeyChecking=no $adminuser@$server.enterprisenet.org << EOF
          echo "Checking for process listening on port $server_port..."
          pid=\$(lsof -i :$server_port -sTCP:LISTEN -t)

          if [ -n "\$pid" ]; then
            echo "Found PID: \$pid"
            kill -9 \$pid
            status=\$?
            if [ \$status -eq 0 ]; then
              echo "Killed PID \$pid successfully"
            else
              echo "Failed to kill PID \$pid (exit code \$status)"
              exit 1
            fi
          else
            echo "No process found listening on port $server_port"
          fi

          pwd
          whoami
          cd /$envName/bin || echo "Directory not found"
          nohup ./startPATservice_$envName.sh > /dev/null 2>&1 &
          EOF
