name: "PAT QA Docker"

on:
  workflow_dispatch:

jobs:
  checkout-013:
    runs-on: self-hosted
    steps:
      - name: Execute Remote Commands
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambscm1@daylnxcpsq013.enterprisenet.org << 'EOF'
          set -xe
          
          cd /home/bambscm1/actions-runner/_work/bcc-patservice/bcc-patservice/ddrgenerator/
          export JAVA_HOME=/usr/local/jdk11
          chmod +x gradlew
          
          nohup ./gradlew clean build -x test --no-daemon --console=plain --stacktrace > gradle_output.log 2>&1 &
          
          while pgrep -f gradlew > /dev/null; do
              sleep 10
          done
          
          docker kill ddrgenerator || true
          docker rm ddrgenerator || true
          docker image rm -f ddrgenerator || true
          
          docker build -t ddrgenerator --file Dockerfile .
          
          cd ../cicd/docker-compose/qa
          docker-compose -f docker-compose.primary.yml up -d
          
          exit 0
          EOF || true
