name: Azure Login and Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for deployment (nonprod or prod)'
        required: true
        default: 'nonprod'
        type: choice
        options:
          - nonprod
          - prod

jobs:
  azure-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.0

    - name: Set Azure Environment Variables
      id: set_env
      run: |
        if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
          echo "ARM_CLIENT_ID=${{ secrets.CRS_AZURE_CLIENT_ID_PROD }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.CRS_AZURE_CLIENT_SECRET_PROD }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.CRS_AZURE_TENANT_ID_PROD }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.CRS_AZURE_SUBSCRIPTION_ID_PROD }}" >> $GITHUB_ENV
        else
          echo "ARM_CLIENT_ID=${{ secrets.CRS_AZURE_CLIENT_ID_NONPROD }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.CRS_AZURE_CLIENT_SECRET_NONPROD }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.CRS_AZURE_TENANT_ID_NONPROD }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.CRS_AZURE_SUBSCRIPTION_ID_NONPROD }}" >> $GITHUB_ENV
        fi

    - name: Login to Azure using CLI
      run: |
        az login --service-principal \
          -u $ARM_CLIENT_ID \
          -p $ARM_CLIENT_SECRET \
          --tenant $ARM_TENANT_ID

    - name: Run Azure CLI Command
      run: az account show

    - name: Set Azure Account Subscription
      run: |
        az account set --subscription $ARM_SUBSCRIPTION_ID

    - name: Check if Resource Group Exists
      id: check_rg
      run: |
        az group exists --name crs-${{ github.event.inputs.environment }}-tfstate-rg

    - name: Check Storage Account Availability
      id: check_storage
      run: |
        az storage account check-name --name crs${{ github.event.inputs.environment }}prodstorageacct
        az storage container exists --account-name crs${{ github.event.inputs.environment }}prodstorageacct --name crs-${{ github.event.inputs.environment }}-tfstate-container
