name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      TF_VAR_namespace:
        description: 'Subscription type for deployment'
        required: true
        default: 'nonprod'
        type: choice
        options:
          - nonprod
          - stage
          - prod
      deployment_type:
        description: 'Deployment type (Bootstrap, Compute, Database, Network)'
        required: true
        default: 'bootstrap'
        type: choice
        options:
          - bootstrap
          - compute
          - database
          - network

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Terraform Version
      run: |
        if [ "${{ github.event.inputs.deployment_type }}" == "network" ]; then
          echo "Using Terraform version 1.60 for Network deployment..."
          echo "TERRAFORM_VERSION=1.60" >> $GITHUB_ENV
        else
          echo "Using Terraform version 1.9.0 for other deployments..."
          echo "TERRAFORM_VERSION=1.9.0" >> $GITHUB_ENV
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Move and Rename Files
      run: |
        echo "Selected Deployment Type: ${{ github.event.inputs.deployment_type }}"
        case "${{ github.event.inputs.deployment_type }}" in
          bootstrap)
            echo "Moving files for Bootstrap..."
            mv -f ./CRS-Azure-Bootstrap-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Bootstrap..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          compute)
            echo "Moving files for Compute..."
            mv -f ./CRS-Azure-Compute-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Compute..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          database)
            echo "Moving files for Database..."
            mv -f ./CRS-Azure-Database-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Database..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          network)
            echo "Moving files for Network..."
            mv -f ./CRS-Azure-Network-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Network..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          *)
            echo "Invalid deployment type selected."
            exit 1
            ;;
        esac

    - name: Configure Git Authentication
      run: |
        git config --global url."https://oauth2:${{ secrets.ICP_GH_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Terraform Init
      run: |
        terraform init -reconfigure \
          -backend-config="resource_group_name=crs-${{ github.event.inputs.TF_VAR_namespace }}-tfstate-rg" \
          -backend-config="storage_account_name=crs${{ github.event.inputs.TF_VAR_namespace }}prodstorageacct" \
          -backend-config="container_name=crs-${{ github.event.inputs.TF_VAR_namespace }}-tfstate-container" \
          -backend-config="key=${{ github.event.inputs.deployment_type }}.tfstate"

    - name: Terraform Plan (Optional for Debugging)
      if: ${{ github.event.inputs.deployment_type == 'network' }}
      run: terraform plan

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve
