name: "Trigger QA Workflow in bcc-patservice"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment"
        required: true
        type: choice
        options:
          - pflqa00
          - pflqa12
          - pflqa22
          - pflqa36
          - pflqa42

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Trigger QA Workflow in bcc-patservice
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/niq-enterprise/bcc-patservice/actions/workflows/qa.yaml/dispatches \
            -d '{"ref":"trn/feature/jan31", "inputs": {"Environment": "${{ github.event.inputs.environment }}"}}'
