apiVersion: v1
kind: Pod
metadata:
  name: container-custom-apparmor-profile
  namespace: kspm-negative-testing
spec:
  containers:
    - name: test-application
      image: e0001meastus2acrcrsl2.azurecr.io/tdex/azcld/kspm/test-application:1.0.0
      resources:
        requests:
          memory: 1Gi
          cpu: 0.5
        limits:
          memory: 1Gi
          cpu: 0.5
      securityContext:
        appArmorProfile:
          type: Localhost
          localhostProfile: k8s-apparmor-example
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
