name: Merge Feature to Develop Branch

on:
  workflow_dispatch:

jobs:
  merge_feature_to_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'feature/test-develop'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Feature to Develop
        run: |
          git config --global user.email "balaji.seetharman@cignahealthcare.com"
          git config --global user.name "C8X6K9_Zilver"

          git fetch origin
          git checkout develop
          git pull --rebase origin develop

          git checkout -b temp_merge_branch feature/test-develop
          git merge --squash develop --strategy-option theirs || true

          git add .
          git commit -m "Merged latest changes from feature/test-develop into develop (Auto-resolved)" || true

          git checkout develop
          git merge temp_merge_branch --no-ff --strategy-option theirs || true

          git pull --rebase origin develop
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zilvertonz/GBS_DAE_Python_ETL.git HEAD:develop --force-with-lease || true
