name: "Server 013 Deployment"

on:
  workflow_dispatch:

jobs:
  server-013:
    runs-on: self-hosted
    steps:
      - name: Setup SSH Access
        run: |
          ssh-agent bash -c 'ssh-add ~/.ssh/vscode; scp -o StrictHostKeyChecking=no -i ~/.ssh/vscode -r /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/* bambscm1@daylnxcpsq013.enterprisenet.org:/home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/'

      - name: Execute Remote Commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambscm1@daylnxcpsq013.enterprisenet.org << 'EOF'
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator
          export JAVA_HOME=/usr/local/jdk11
          chmod 755 gradlew
          ./gradlew clean build -x test

          docker kill ddrgenerator || true
          docker rm ddrgenerator || true
          docker image rm -f ddrgenerator || true

          cd /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator
          docker build -t ddrgenerator --file Dockerfile .

          cd /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/cicd/docker-compose/qa
          docker-compose -f docker-compose.primary.yml up -d
          EOF
