name: "PAT QA Build"

on:
  workflow_dispatch:

jobs:
  checkout-014:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq014
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: "niq-enterprise/bcc-patservice"
          ref: "trn/1.0/controlled"

  server-014:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq014
    needs: checkout-014
    steps:
      - name: Build and Deploy on Server 014
        run: |
          export JAVA_HOME=/usr/local/jdk11
          chmod 755 ddrgenerator/gradlew
          cd ddrgenerator
          ./gradlew clean build -x test
          
          docker kill ddrgenerator || true
          docker rm ddrgenerator || true
          docker image rm -f ddrgenerator || true
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator
          docker build -t ddrgenerator --file Dockerfile .
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/cicd/docker-compose/qa
          docker-compose -f docker-compose.primary.yml up -d

  checkout-015:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq015
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: "niq-enterprise/bcc-patservice"
          ref: "trn/1.0/controlled"

  server-015:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq015
    needs: checkout-015
    steps:
      - name: Build and Deploy on Server 015
        run: |
          export JAVA_HOME=/usr/local/jdk11
          chmod 755 ddrgenerator/gradlew
          cd ddrgenerator
          ./gradlew clean build -x test
          
          docker kill ddrgenerator || true
          docker rm ddrgenerator || true
          docker image rm -f ddrgenerator || true
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq015/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator
          docker build -t ddrgenerator --file Dockerfile .
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq015/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/cicd/docker-compose/qa
          docker-compose -f docker-compose.primary.yml up -d

  checkout-016:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq016
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: "niq-enterprise/bcc-patservice"
          ref: "trn/1.0/controlled"

  server-016:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq016
    needs: checkout-016
    steps:
      - name: Build and Deploy on Server 016
        run: |
          export JAVA_HOME=/usr/local/jdk11
          chmod 755 ddrgenerator/gradlew
          cd ddrgenerator
          ./gradlew clean build -x test
          
          docker kill ddrgenerator || true
          docker rm ddrgenerator || true
          docker image rm -f ddrgenerator || true
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq016/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator
          docker build -t ddrgenerator --file Dockerfile .
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq016/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/cicd/docker-compose/qa
          docker-compose -f docker-compose.primary.yml up -d

  server-013:
    runs-on: consumer-panel-services-agent_qa_daylnxcpsq014
    needs: server-014
    steps:
      - name: Copy Files to Server 013
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/vscode -r /home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/* bambscm1@daylnxcpsq013.enterprisenet.org:/home/bambscm1/adlm_jenkins/daylnxcpsq013/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/
      
      - name: Build and Deploy on Server 013
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambscm1@daylnxcpsq013.enterprisenet.org << EOF
          export JAVA_HOME=/usr/local/jdk11
          chmod 755 /home/bambscm1/adlm_jenkins/daylnxcpsq013/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator/gradlew
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq013/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/ddrgenerator
          ./gradlew clean build -x test
          
          docker kill ddrgenerator || true
          docker rm ddrgenerator || true
          docker image rm -f ddrgenerator || true
          
          docker build -t ddrgenerator --file Dockerfile .
          
          cd /home/bambscm1/adlm_jenkins/daylnxcpsq013/workspace/Consumer_Panel_Services_Home/Github/PAT/pat-docker-qa/cicd/docker-compose/qa
          docker-compose -f docker-compose.primary.yml up -d
          EOF
