name: QA PAT

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the Environment'
        required: true
        type: choice
        options:
          - pflqa00
          - pflqa12
          - pflqa22
          - pflqa36

jobs:
  setup:
    runs-on: qa-runner
    steps:
      - name: Set Admin User and Path
        id: set_vars
        run: |
          case "${{ github.event.inputs.Environment }}" in
            pflqa12)
              echo "ADMIN_USR=pfmgr2" >> $GITHUB_ENV
              echo "PATH_ENV=pflqa12/" >> $GITHUB_ENV
              ;;
            pflqa22)
              echo "ADMIN_USR=pfmgr3" >> $GITHUB_ENV
              echo "PATH_ENV=pflqa22/" >> $GITHUB_ENV
              ;;
            pflqa36)
              echo "ADMIN_USR=pfmgr4" >> $GITHUB_ENV
              echo "PATH_ENV=pflqa36/" >> $GITHUB_ENV
              ;;
            pflqa00)
              echo "ADMIN_USR=pfmgr" >> $GITHUB_ENV
              echo "PATH_ENV=pflqa00/" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid Environment choice."
              exit 1
              ;;
          esac

      - name: Display Parameters
        run: |
          echo "Environment: ${{ github.event.inputs.Environment }}"
          echo "Admin User: ${{ env.ADMIN_USR }}"
          echo "Path: ${{ env.PATH_ENV }}"

  pat:
    needs: setup
    runs-on: qa-runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Print current directory
        run: pwd

      - name: Debug Variables
        run: |
          echo "Admin User: ${{ env.ADMIN_USR }}"
          echo "Environment: ${{ github.event.inputs.Environment }}"
          echo "SSH Command: ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode ${{ env.ADMIN_USR }}@daylnxcpsq014.enterprisenet.org 'ls'"

      - name: Execute SSH Commands for PAT
        env:
          ADMIN_USR: ${{ env.ADMIN_USR }}
        run: |
          echo "Running as: $ADMIN_USR"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "chmod -R 750 /${{ github.event.inputs.Environment }}/bin/*"
