jobs:
  test-sql-connection:
    runs-on: ubuntu-latest  # Use the appropriate runner
    steps:
      - name: Install Kerberos utilities
        run: sudo apt-get update && sudo apt-get install -y krb5-user libkrb5-dev

      - name: Authenticate with Kerberos
        env:
          KRB_USER: "C8X6K9@INTERNAL.CIGNA.COM"
          KRB_PASSWORD: ${{ secrets.KERBEROS_PASSWORD }}
        run: |
          echo "$KRB_PASSWORD" | kinit "$KRB_USER"

      - name: Verify Kerberos Ticket
        run: klist

      - name: Run SQL Server Connection Test
        run: python testsqlserver.py
