name: Configure Kerberos

on: 
  push:
    branches:
      - main

jobs:
  configure-kerberos:
    runs-on: ubuntu-latest

    steps:
      - name: Create /etc/krb5.conf file
        run: |
          sudo tee /etc/krb5.conf > /dev/null <<EOF
          [realms]
           INTERNAL.CIGNA.COM = {
            kdc = 10.204.64.2
           }

          [domain_realm]
           .INTERNAL.CIGNA.COM = INTERNAL.CIGNA.COM
           INTERNAL.CIGNA.COM = INTERNAL.CIGNA.COM
          EOF

      - name: Verify Kerberos Configuration
        run: cat /etc/krb5.conf
