name: SQL Server Connection Test

on:
  push:
    branches:
      - main

jobs:
  test-sql-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev
          curl -O https://packages.microsoft.com/config/ubuntu/20.04/prod.list
          sudo mv prod.list /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Install Python Dependencies
        run: |
          pip install pyodbc

      - name: Run SQL Server Connection Test
        run: python test_sqlserver.py
