name: QA PAT

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the Environment'
        required: true
        type: choice
        options:
          - pflqa00
          - pflqa12
          - pflqa22
          - pflqa36

jobs:
  pat:
    runs-on: qa-runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          echo "ORG_PATH=/home/bambscm1/adlm_jenkins/daylnxcpsq014/workspace/Consumer_Panel_Services_Home/Github/PAT/PAT_QA/patrepo/" >> $GITHUB_ENV
          echo "TMP_PATH=/tmp/pat/" >> $GITHUB_ENV

      - name: Set Permissions for Temporary Path
        run: chmod -R 755 $TMP_PATH

      - name: Execute SSH Commands
        env:
          ADMIN_USR: ${{ env.ADMIN_USR }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "chmod 750 /${{ github.event.inputs.Environment }}/bin"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "chmod -R 750 /${{ github.event.inputs.Environment }}/bin/*"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "cp -rf ${ORG_PATH}ETL/config/SQA/${path_env}* /${{ github.event.inputs.Environment }}/bin/etl/config/"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "cp -rf ${ORG_PATH}ETL/scripts/* /${{ github.event.inputs.Environment }}/bin/etl/scripts/"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "cp -rf ${ORG_PATH}ETL/sql/* /${{ github.event.inputs.Environment }}/bin/etl/sql/"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "cp -rf ${ORG_PATH}ETL/ref/* /${{ github.event.inputs.Environment }}/bin/etl/ref/"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vscode "${ADMIN_USR}@daylnxcpsq014.enterprisenet.org" "cp -rf ${ORG_PATH}unix/PFW_UNIX/shellscripts/* /${{ github.event.inputs.Environment }}/bin/"
