name: Trigger QA PATService Workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the Environment'
        required: true
        type: choice
        options:
          - pflqa00
          - pflqa12
          - pflqa22
          - pflqa36
          - pflqa42

jobs:
  trigger-bcc-patservice:
    runs-on: self-host
    steps:
      - name: Trigger Workflow in bcc-patservice
        env:
          GH_TOKEN: ${{ secrets.Pat_token }} 
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token $GH_TOKEN" \
               https://api.github.com/repos/niq-enterprise/bcc-patservice/actions/workflows/qa.yaml/dispatches \
               -d '{
                 "ref": "trn/feature/jan31",
                 "inputs": {
                   "Environment": "${{ github.event.inputs.Environment }}"
                 }
               }'
