name: SQL Server SQLCMD Auth Test

on:
  push:
    branches:
      - test-windows-server

jobs:
  test-sqlcmd-auth:
    runs-on: zilverton-private-x64-windows

    steps:
      - name: Run sqlcmd to Test SQL Server Authentication
        run: |
          sqlcmd -S HSTNCMSRDIDEV01.healthspring.inside -U INTERNAL\\c8x6k9 -P "Dev2s@mpath" -Q "SELECT @@VERSION"
        shell: cmd
