
jobs:
  validate-actor:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Actor
        run: echo "GitHub actor: '${{ github.actor }}'"

      - name: Validate Actor
        run: |
          echo "🧾 Comparing: input.user='${{ github.event.inputs.user }}' vs actor='${{ github.actor }}'"
          if [ "${{ github.event.inputs.user }}" != "${{ github.actor }}" ]; then
            echo "❌ Unauthorized actor: ${{ github.actor }}"
            exit 1
          else
            echo "✅ Authorized actor: ${{ github.actor }}"
          fi
