apiVersion: v1
kind: Pod
metadata:
  name: fim-test-var-log
  namespace: o11y-collectors-test
spec:
  containers:
  - name: test
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: varlog
      mountPath: /var/log/pods
      readOnly: false
  volumes:
  - name: varlog
    hostPath:
      path: /var/log/pods
      type: Directory


===
# Read (should NOT alert)
kubectl exec -it fim-test-var-log -n o11y-collectors-test -- cat /var/log/pods/some.log

# Write (should trigger alert)
kubectl exec -it fim-test-var-log -n o11y-collectors-test -- sh -c 'echo "fim write test" >> /var/log/pods/test.log'
