name: Azure Login Using CLI

on:
  workflow_dispatch:

jobs:
  azure-login-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure using CLI
      run: |
        az login --service-principal \
          -u ${{ secrets.CRS_AZURE_CLIENT_ID_NONPROD }} \
          -p ${{ secrets.CRS_AZURE_CLIENT_SECRET_NONPROD }} \
          --tenant ${{ secrets.CRS_AZURE_TENANT_ID_NONPROD }}

    - name: Run Azure CLI Command
      run: az account show
