name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      TF_VAR_namespace:
        description: 'Subscription type for deployment'
        required: true
        default: 'nonprod'
        type: choice
        options:
          - nonprod
          - stage
          - prod
      deployment_type:
        description: 'Deployment type (Bootstrap, Compute, Database, Network)'
        required: true
        default: 'bootstrap'
        type: choice
        options:
          - bootstrap
          - compute
          - database
          - network

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Move and Rename Files
      run: |
        echo "Selected Deployment Type: ${{ github.event.inputs.deployment_type }}"
        case "${{ github.event.inputs.deployment_type }}" in
          bootstrap)
            echo "Moving files for Bootstrap..."
            mv -f ./CRS-Azure-Bootstrap-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Bootstrap..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          compute)
            echo "Moving files for Compute..."
            mv -f ./CRS-Azure-Compute-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Compute..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          database)
            echo "Moving files for Database..."
            mv -f ./CRS-Azure-Database-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Database..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          network)
            echo "Moving files for Network..."
            mv -f ./CRS-Azure-Network-Infrastructure/* ./
            echo "Copying and renaming Optumfile for Network..."
            cp optumfiles/Optumfile-${{ github.event.inputs.TF_VAR_namespace }}.yml ./Optumfile.yml
            ;;
          *)
            echo "Invalid deployment type selected."
            exit 1
            ;;
        esac
