name: Azure CLI Operations

on:
  workflow_dispatch:

jobs:
  azure-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Azure using Service Principal
      run: |
        az login --service-principal \
          -u ${{ secrets.CRS_AZURE_CLIENT_ID_NONPROD }} \
          -p ${{ secrets.CRS_AZURE_CLIENT_SECRET_NONPROD }} \
          --tenant ${{ secrets.CRS_AZURE_TENANT_ID_NONPROD }}

    - name: Set Azure Account Subscription
      run: |
        az account set --subscription "e0e5bf14-0e68-4675-a9c1-84e450ab6f89"

    - name: Check if Resource Group Exists
      id: check_rg
      run: |
        az group exists --name crs-prod-tfstate-rg

    - name: Log Resource Group Existence
      run: |
        echo "Resource group exists: ${{ steps.check_rg.outputs.stdout }}"

    - name: Check Storage Account Availability
      id: check_storage
      run: |
        az storage account check-name --name crsprodstorageacct

    - name: Log Storage Account Check
      run: |
        echo "Storage account availability: ${{ steps.check_storage.outputs.stdout }}"
