name: Azure Login

on:
  workflow_dispatch:

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CRS_AZURE_CLIENT_ID_NONPROD }}
        client-secret: ${{ secrets.CRS_AZURE_CLIENT_SECRET_NONPROD }}
        tenant-id: ${{ secrets.CRS_AZURE_TENANT_ID_NONPROD }}

    - name: Verify Azure login
      run: az account show
