name: Azure Login Without Subscription

on:
  workflow_dispatch:

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure (No Subscription Context)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CRS_AZURE_CLIENT_ID_NONPROD }}
        client-secret: ${{ secrets.CRS_AZURE_CLIENT_SECRET_NONPROD }}
        tenant-id: ${{ secrets.CRS_AZURE_TENANT_ID_NONPROD }}
        allow-no-subscriptions: true

    - name: Run Azure CLI Command
      run: az ad user list
