name: Azure Deploy

on:
  workflow_dispatch:

jobs:
  terraform-deploy:
    runs-on: [uhg-runner]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git Authentication
        run: |
          echo "#!/bin/sh" > git-askpass.sh
          echo "echo ${{ secrets.ICP_GH_TOKEN }}" >> git-askpass.sh
          chmod +x git-askpass.sh
          echo "GIT_ASKPASS script created."
        env:
          GITHUB_TOKEN: ${{ secrets.ICP_GH_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: |
          export GIT_ASKPASS="$(pwd)/git-askpass.sh"
          terraform init -backend=false -no-color
        env:
          GIT_ASKPASS: "$(pwd)/git-askpass.sh"

      - name: Terraform Plan
        run: |
          export GIT_ASKPASS="$(pwd)/git-askpass.sh"
          terraform plan -var="TF_VAR_namespace=${{ github.event.inputs.TF_VAR_namespace }}"
        env:
          GIT_ASKPASS: "$(pwd)/git-askpass.sh"

      - name: Terraform Apply
        run: |
          export GIT_ASKPASS="$(pwd)/git-askpass.sh"
          terraform apply -auto-approve
        env:
          GIT_ASKPASS: "$(pwd)/git-askpass.sh"
