name: "Aggengine Image Build"

on: 
  push:
    branches: 
      - "feature/*"
    paths-ignore: 
      - ".github/*"
    tags:
      - '*'  # Triggers on any tag push
  schedule:
    - cron: '30 5 * * 1-5'
    - cron: '30 10 * * 1-5'
    - cron: '0 15 * * 1-5'
    - cron: '0 19 * * 1-5'

jobs:
  kv:
    runs-on: self-hosted
    steps:
      - name: fetch secrets
        id: kv
        uses: niq-actions/az-kv-management@v2.3.1
        env:
            AZURE_CLIENT_ID: ${{ secrets.OMNSHO_SP_NP_APPID }}
            AZURE_CLIENT_SECRET: ${{ secrets.OMNSHO_SP_NP_PASSWORD }}
            AZURE_TENANT_ID: ${{ secrets.OMNSHO_SP_NP_TENANT }}
        with:
            kv_name: OMNSHOKVAUTOUS
            summary: false
            type: get
            secretname: artifactory-password
    outputs:
      artifactory-password: ${{ steps.kv.outputs.artifactory-password }}

  CCOE-BUILD:
    needs: [kv]
    runs-on: self-hosted
    uses: niq-actions/niq-build/.github/workflows/build.yml@v3
    secrets: inherit
    with:
      image_name: "aggengapi"
      dev_acr: "omnshodevacreastus2.azurecr.io"
      prod_acr: "omnshoprodacreastus2.azurecr.io"
      build-args: |
        BRANCH=${{ github.ref_name }}
        ARTIFACTORY_USERNAME=omnishopper2srv
        ARTIFACTORY_PASSWORD=${{ needs.kv.outputs.artifactory-password }}
      push_image: true
      wiz_feature_scan: false
      wiz_username: WIZ_USERNAME
      wiz_password: WIZ_PASSWORD
      service_principal: OMNSHO_SP_NP
      path: "./Dockerfile"
      lfs: false

  # Job for the scheduled build for release/develop branch
  build-scheduled:
    if: github.event_name == 'schedule'
    runs-on: self-hosted
    uses: niq-actions/niq-build/.github/workflows/build.yml@v3
    secrets: inherit
    with:
      image_name: "aggengapi"
      dev_acr: "omnshodevacreastus2.azurecr.io"
      prod_acr: "omnshoprodacreastus2.azurecr.io"
      build-args: |
        BRANCH=${{ github.ref_name }}
        ARTIFACTORY_USERNAME=omnishopper2srv
        ARTIFACTORY_PASSWORD=${{ needs.kv.outputs.artifactory-password }}
      push_image: true
      wiz_feature_scan: false
      wiz_username: WIZ_USERNAME
      wiz_password: WIZ_PASSWORD
      service_principal: OMNSHO_SP_NP
      path: "./Dockerfile"
      lfs: false
      tag: "00-00-00"

  # Job for building when a tag is pushed
  build-on-tag-push:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    uses: niq-actions/niq-build/.github/workflows/build.yml@v3
    secrets: inherit
    with:
      image_name: "aggengapi"
      dev_acr: "omnshodevacreastus2.azurecr.io"
      prod_acr: "omnshoprodacreastus2.azurecr.io"
      build-args: |
        BRANCH=${{ github.ref_name }}
        ARTIFACTORY_USERNAME=omnishopper2srv
        ARTIFACTORY_PASSWORD=${{ needs.kv.outputs.artifactory-password }}
      push_image: true
      wiz_feature_scan: false
      wiz_username: WIZ_USERNAME
      wiz_password: WIZ_PASSWORD
      service_principal: OMNSHO_SP_NP
      path: "./Dockerfile"
      lfs: false
      tag: "${{ github.ref#refs/tags/ }}"
